# Ajouter un job pour staging
deploy-staging:
  runs-on: ubuntu-latest
  needs: build
  if: github.ref == 'refs/heads/staging'
  environment:
    name: 'Staging'
    url: ${{ steps.deploy-to-staging.outputs.webapp-url }}

  steps:
    # ... mêmes étapes avec slot-name: 'staging'
